---

scenario:
  name: layouts

driver:
  name: docker

dependency: {}

platforms:
  - name: instance1
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - minio

  - name: instance2
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - minio

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    diff: True
    v: True
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ./playbook.yml

lint: |
  set -e
  ansible-lint

verifier:
  name: testinfra
  options:
    vvv: True
    s: true
  additional_files_or_dirs:
    - ../resources/tests/
