---

- hosts: all
  any_errors_fatal: true
  roles:
    - ansible-minio
  vars_files:
    - ./../resources/vars.yml
  vars:
    minio_server_artifact_url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2023-07-07T07-13-57Z
    minio_server_artifact_checksum: sha256:15d762671436cf383f9cc6667260e6c1298c25c8d7009576f709c3823e4a494d
    minio_client_artifact_url: https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2023-07-07T05-25-51Z
    minio_client_artifact_checksum: sha256:205a2dc5a49dc467f78228c43c7d368e376c6cc14492597a7c4fe195c291f074
    minio_server_envfile: "/opt/minio"
    minio_server_addr: ":80"
    minio_server_datadirs:
      - "/srv/data1"
      - "/srv/data2"
      - "/srv/data3"
      - "/srv/data4"
