---

- hosts: all
  any_errors_fatal: true
  roles:
    - ansible-minio
  vars:
    minio_server_datadirs:
      - "/test1"
      - "/test2"
      - "/test3"
      - "/test4"
    minio_server_cluster_nodes:
      - "http://{{ ansible_hostname }}:9091/test1"
      - "http://{{ ansible_hostname }}:9091/test2"
      - "http://{{ ansible_hostname }}:9091/test3"
      - "http://{{ ansible_hostname }}:9091/test4"
